### ISSUE TITLE
Tome Rater (PWP)

### ISSUE THREAD

**Issue by asadmehdi785** [martinloesethjensen/Capstone-Project-Tome-Rater#1]
### Criteria 1: Valid Python Code
* _Score Level:_ 4
* _Comment(s):_ Code included runs without any errors.
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4
* _Comment(s):_ Code produces the suite of functions and classes required of it and calls them in an appropriate order.
 
### Criteria 3: Software Architecture
* _Score Level:_ 4
* _Comment(s):_ Code is separated into distinct classes and functions each which are invoked for their own purposes. 
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ 4
* _Comment(s):_ Code uses language features appropriately. If a task can be solved with a Python language feature, it is.
 
### Overall Score: 16/16
Overall, outstanding job with this project! You did a great job writing the classes and methods required in the project, and I liked how you used Python features such as list comprehension to help implement some of those methods concisely. Well done!

Excellent job overall. I hope you enjoyed the course!

**Comment by martinloesethjensen** [comment]
Thanks for the review! I'm glad I fulfilled all the requirements. 

I really enjoyed this course and it taught me a lot. I liked the interactive coding in Codecademy and I think the best way to learn is by doing.
